-- 创建表
drop table person if exists;
create table person (
  person_id int generated by default as identity(start with 1, increment by 1),
  person_name varchar(32),
  nick_name varchar(32),
  title varchar(16),
  age int,
  company_id int,
  primary key(person_id)
);

drop table company if exists;
create table company (
  company_id int generated by default as identity,
  company_name varchar(32),
  city varchar(16),
  primary key(company_id)
);

